/**
 * @module        projectInit
 * @description   项目初始化命令，从模板创建项目配置和目录结构
 *
 * @author        eddy
 * @organization  wykj
 * @ownership     wykj/eddy
 *
 * @created       2026-03-19
 * @updated       2026-04-03
 *
 * @role          command
 * @layer         command
 * @boundedContext system
 *
 * @trigger       sps init <project> [--force]
 * @inputs        项目名、--force 覆盖标志
 * @outputs       初始化后的项目目录和配置文件
 * @workflow      1. 查找模板目录 → 2. 创建项目目录 → 3. 复制模板文件 → 4. 写入配置
 */
import { chmodSync, copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { createInterface } from 'node:readline';
import { fileURLToPath } from 'node:url';
import { Logger } from '../core/logger.js';

const HOME = process.env.HOME || '/home/coral';
const __dirname = dirname(fileURLToPath(import.meta.url));

// Look for project-template relative to the package root (works for both npm install and source)
function findTemplateDir(): string {
  // When installed via npm: dist/commands/projectInit.js → ../../project-template
  const npmPath = resolve(__dirname, '..', '..', 'project-template');
  if (existsSync(npmPath)) return npmPath;
  // When running from source repo: src/commands/ → ../../../project-template
  const srcPath = resolve(__dirname, '..', '..', '..', 'project-template');
  if (existsSync(srcPath)) return srcPath;
  // Legacy fallback
  const legacyPath = resolve(HOME, 'jarvis-skills', 'coding-work-flow', 'project-template');
  if (existsSync(legacyPath)) return legacyPath;
  return npmPath; // default, will fail gracefully below
}

const TEMPLATE_DIR = findTemplateDir();

export async function executeProjectInit(
  project: string,
  flags: Record<string, boolean>,
): Promise<void> {
  const log = new Logger('project-init', project);

  if (!project) {
    log.error('Usage: sps project init <project>');
    process.exit(2);
  }

  const instanceDir = resolve(HOME, '.coral', 'projects', project);

  if (existsSync(instanceDir) && !flags.force) {
    log.error(`Project directory already exists: ${instanceDir}`);
    log.info('Use --force to overwrite templates (conf will NOT be overwritten)');
    process.exit(1);
  }

  // Create directory structure
  const dirs = [
    instanceDir,
    resolve(instanceDir, 'logs'),
    resolve(instanceDir, 'pm_meta'),
    resolve(instanceDir, 'runtime'),
  ];

  for (const dir of dirs) {
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
      log.ok(`Created ${dir}`);
    }
  }

  // Generate conf — interactive if new, skip if exists
  const confDst = resolve(instanceDir, 'conf');
  if (!existsSync(confDst) || flags.force) {
    const rl = createInterface({ input: process.stdin, output: process.stdout });
    const ask = (question: string, defaultValue?: string): Promise<string> => {
      const suffix = defaultValue ? ` [${defaultValue}]` : '';
      return new Promise((res) => {
        rl.question(`  ${question}${suffix}: `, (answer) => {
          res(answer.trim() || defaultValue || '');
        });
      });
    };

    console.log(`\n  Configure project: ${project}`);
    console.log('  Press Enter to accept default value.\n');

    // Required
    const projectDir = await ask('Repository path', resolve(HOME, 'projects', project));
    const pmTool = await ask('PM backend (markdown/plane/trello)', 'markdown');
    const mergeBranch = await ask('Merge target branch', 'main');
    const workerTool = await ask('Default worker agent (claude/codex)', 'claude');
    const maxWorkers = await ask('Max concurrent workers', '1');

    // Git remote (optional)
    console.log('\n  ── Git Remote (optional, leave blank to skip) ──');
    const gitlabProject = await ask('Git remote project path (e.g. user/repo)', '');
    const gitlabProjectId = gitlabProject ? await ask('GitLab project ID (number, blank if GitHub)', '') : '';

    // PM-specific
    let planeProjectId = '';
    let trelloBoardId = '';
    if (pmTool === 'plane') {
      console.log('\n  ── Plane ──');
      planeProjectId = await ask('Plane project ID', '');
    } else if (pmTool === 'trello') {
      console.log('\n  ── Trello ──');
      trelloBoardId = await ask('Trello board ID', '');
    }

    // Notification
    console.log('\n  ── Notifications ──');
    const matrixRoomId = await ask('Matrix room ID (blank to use global)', '');

    rl.close();

    // Build conf — only the user's actual values (clean, minimal)
    const confLines: string[] = [
      `# SPS Project Config — ${project}`,
      `# Generated by: sps project init (${new Date().toISOString().slice(0, 10)})`,
      `# Full parameter reference: conf.example`,
      '',
      `export PROJECT_NAME="${project}"`,
      `export PROJECT_DIR="${projectDir}"`,
      '',
    ];
    if (gitlabProject) confLines.push(`export GITLAB_PROJECT="${gitlabProject}"`);
    if (gitlabProjectId) confLines.push(`export GITLAB_PROJECT_ID="${gitlabProjectId}"`);
    confLines.push(`export GITLAB_MERGE_BRANCH="${mergeBranch}"`);
    confLines.push('');
    confLines.push(`export PM_TOOL="${pmTool}"`);
    if (pmTool === 'plane' && planeProjectId) confLines.push(`export PLANE_PROJECT_ID="${planeProjectId}"`);
    if (pmTool === 'trello' && trelloBoardId) confLines.push(`export TRELLO_BOARD_ID="${trelloBoardId}"`);
    confLines.push('export PIPELINE_LABEL="AI-PIPELINE"');
    confLines.push('export MR_MODE="none"');
    confLines.push('');
    confLines.push(`export WORKER_TOOL="${workerTool}"`);
    confLines.push('export WORKER_TRANSPORT="acp-sdk"');
    confLines.push(`export MAX_CONCURRENT_WORKERS=${maxWorkers}`);
    confLines.push('export MAX_ACTIONS_PER_TICK=3');
    confLines.push('');
    confLines.push('export INPROGRESS_TIMEOUT_HOURS=2');
    confLines.push('export MONITOR_AUTO_QA=true');
    confLines.push('export CONFLICT_DEFAULT="serial"');
    if (matrixRoomId) {
      confLines.push('');
      confLines.push(`export MATRIX_ROOM_ID="${matrixRoomId}"`);
    }
    confLines.push('');

    writeFileSync(confDst, confLines.join('\n') + '\n');
    chmodSync(confDst, 0o600);
    log.ok('Generated conf with your settings');
  } else {
    log.info('conf already exists, skipping (use --force to regenerate)');
  }

  // Always write conf.example — full parameter reference (English)
  const confExamplePath = resolve(instanceDir, 'conf.example');
  writeFileSync(confExamplePath, `# ══════════════════════════════════════════════════════════════════
# SPS Project Config — Full Parameter Reference
# ══════════════════════════════════════════════════════════════════
# This file is for reference only. SPS does NOT load it.
# Copy parameters you need into the 'conf' file in the same directory.
# ══════════════════════════════════════════════════════════════════

# ── Project Info (required) ──────────────────────────────────────
# PROJECT_NAME: Unique project identifier used internally by SPS
export PROJECT_NAME="my-project"
# PROJECT_DIR: Local path to the code repository
export PROJECT_DIR="$HOME/projects/my-project"

# ── Git Remote ───────────────────────────────────────────────────
# GITLAB_PROJECT: GitLab/GitHub project path (format: user/repo or group/repo)
#   Used for doctor checks, MR creation, etc. Leave blank to skip GitLab API features.
export GITLAB_PROJECT="user/repo"
# GITLAB_PROJECT_ID: GitLab numeric project ID (GitLab only; leave blank for GitHub)
#   Find it at GitLab > Settings > General
export GITLAB_PROJECT_ID="42"
# GITLAB_MERGE_BRANCH: Target branch for worker code merges
export GITLAB_MERGE_BRANCH="main"

# ── PM Backend ───────────────────────────────────────────────────
# PM_TOOL: Task management backend
#   - markdown: Local markdown files (zero-config, good for solo projects)
#   - plane: Plane CE/Cloud (requires PLANE_* credentials in ~/.coral/env)
#   - trello: Trello (requires TRELLO_* credentials in ~/.coral/env)
export PM_TOOL="markdown"
# PLANE_PROJECT_ID: Plane project ID (only when PM_TOOL=plane)
# export PLANE_PROJECT_ID=""
# TRELLO_BOARD_ID: Trello board ID (only when PM_TOOL=trello)
# export TRELLO_BOARD_ID=""
# TRELLO_ACCOUNT: Multi-account Trello (maps to TRELLO_*_<account> vars in env)
# export TRELLO_ACCOUNT="default"

# ── Pipeline Control ────────────────────────────────────────────
# PIPELINE_LABEL: Label that marks a card for pipeline processing (required on each card)
export PIPELINE_LABEL="AI-PIPELINE"
# MR_MODE: Merge request mode
#   - none: Worker pushes directly to target branch (default, recommended)
#   - create: Worker creates a GitLab MR (requires GITLAB_PROJECT_ID)
export MR_MODE="none"

# ── Worker / Agent ───────────────────────────────────────────────
# WORKER_TOOL: Default AI agent (can be overridden per-stage in pipeline YAML)
#   Values: claude / codex
export WORKER_TOOL="claude"
# WORKER_TRANSPORT: Worker communication protocol (fixed, do not change)
export WORKER_TRANSPORT="acp-sdk"
# MAX_CONCURRENT_WORKERS: Maximum parallel workers
#   Determines how many cards can be processed simultaneously. Start with 1.
export MAX_CONCURRENT_WORKERS=1
# MAX_ACTIONS_PER_TICK: Max new tasks launched per tick cycle
export MAX_ACTIONS_PER_TICK=3
# DEFAULT_WORKER_SKILLS: Skill profiles loaded by all workers (comma-separated)
#   Can also use skill:xxx labels on individual cards
#   Available: fullstack, frontend, backend, phaser, typescript, reviewer, architect, etc.
# export DEFAULT_WORKER_SKILLS="fullstack"
# ACP_AGENT: Override agent for integrate stage (defaults to WORKER_TOOL)
# export ACP_AGENT="claude"

# ── Timeouts & Policies ─────────────────────────────────────────
# INPROGRESS_TIMEOUT_HOURS: Max hours a worker can stay in Inprogress
#   After timeout, MonitorEngine marks it as STALE-RUNTIME
export INPROGRESS_TIMEOUT_HOURS=2
# WORKER_LAUNCH_TIMEOUT_S: Worker spawn timeout (seconds)
#   If no output after N seconds, spawn is considered failed
# export WORKER_LAUNCH_TIMEOUT_S=120
# WORKER_IDLE_TIMEOUT_M: Worker idle timeout (minutes)
#   If no new output for N minutes, worker is considered stuck
# export WORKER_IDLE_TIMEOUT_M=30
# WORKER_RESTART_LIMIT: Max auto-retry count on worker failure
# export WORKER_RESTART_LIMIT=2
# MONITOR_AUTO_QA: Auto-advance to QA when stale runtime detected
#   true = auto-advance (for fully automated pipelines)
#   false = only label STALE-RUNTIME, requires manual action
export MONITOR_AUTO_QA=true
# CONFLICT_DEFAULT: Default conflict domain policy (for cards without conflict: labels)
#   serial = default to serial (safe, one card at a time)
#   parallel = default to parallel
export CONFLICT_DEFAULT="serial"
# TICK_LOCK_TIMEOUT_MINUTES: Tick lock timeout (minutes), prevents concurrent ticks
# export TICK_LOCK_TIMEOUT_MINUTES=10

# ── Notifications ────────────────────────────────────────────────
# MATRIX_ROOM_ID: Matrix notification room (project-level override; blank uses ~/.coral/env global)
# export MATRIX_ROOM_ID="!roomid:server.com"

# ── Path Overrides (usually no need to change) ──────────────────
# WORKTREE_DIR: Worker worktree root (default: ~/.coral/worktrees/<project>/)
# export WORKTREE_DIR=""
# LOGS_DIR: Log directory (default: ~/.coral/projects/<project>/logs/)
# export LOGS_DIR=""
`);
  log.ok('Updated conf.example (full parameter reference)');

  // Create empty pipeline_order.json if not exists
  const orderFile = resolve(instanceDir, 'pipeline_order.json');
  if (!existsSync(orderFile)) {
    writeFileSync(orderFile, '[]\n');
    log.ok('Created empty pipeline_order.json');
  }

  // Create/update pipelines directory with sample template
  const pipelinesDir = resolve(instanceDir, 'pipelines');
  if (!existsSync(pipelinesDir)) mkdirSync(pipelinesDir, { recursive: true });
  {
    const samplePath = resolve(pipelinesDir, 'sample.yaml.example');
    writeFileSync(samplePath, `# ══════════════════════════════════════════════════════════════════
# SPS Pipeline Configuration
# ══════════════════════════════════════════════════════════════════
# To activate: copy this file to project.yaml
#   cp sample.yaml.example project.yaml
#
# Docs: sps-pipeline skill or docs/design/17-pipeline-configuration-design.md
# ══════════════════════════════════════════════════════════════════

# mode: Pipeline execution mode
#   - project: Event-driven state machine, continuous card-driven pipeline (this template)
#   - steps: Linear step sequence, runs once then exits
mode: project

# ── Card States ──────────────────────────────────────────────────
# Define card state names as they appear in your PM board.
# Only 3 fixed roles required: backlog (entry), ready (prepared), done (finished).
# Intermediate states are defined by each stage's card_state and on_complete.
#
# For Plane/Trello backends, names must match PM column names exactly.
# For markdown backend, names become subdirectories under cards/.
pm:
  card_states:
    planning: Planning     # Requirement pool (user-managed, SPS does not touch)
    backlog: Backlog       # Confirmed and queued (SchedulerEngine starts here)
    ready: Todo            # Environment ready (branch + worktree created, awaiting worker)
    active: Inprogress     # In development (worker is actively coding)
    review: QA             # Awaiting merge (code complete, waiting for merge to target branch)
    done: Done             # Completed (merged and resources released)

# ── Stage Definitions ────────────────────────────────────────────
# Stages define the pipeline execution phases. Minimum 1, no upper limit.
#
# Field reference:
#   name:         Stage name (unique identifier)
#   trigger:      Trigger condition (which card state activates this stage)
#   card_state:   Card state while this stage is active
#   agent:        AI agent to use (claude / codex / gemini)
#   profile:      Skill profile name (optional, comma-separated for multiple)
#   completion:   Completion detection strategy
#     - git-evidence:      Branch has new commits and is pushed to remote
#     - fast-forward-merge: Branch is merged into target branch
#     - exit-code:         Worker process exit code (0 = success)
#   on_complete:  Action on success (move_card <target_state>)
#   on_fail:      Action on failure
#     action:     "label <LABEL_NAME>" (add label to card)
#     comment:    Comment text added to card
#   queue:        Queue strategy (optional)
#     - fifo:     Serial execution (one card at a time, prevents merge conflicts)
#   timeout:      Timeout duration (optional, format: 30s / 5m / 2h)
#
# Execution rules:
#   - First stage handles prepare (creates feature branch + worktree)
#   - Last stage handles release (cleans worktree + releases resources)
#   - In tick loop, later stages run first (QA before new development, prevents starvation)

stages:
  # ── Stage 1: Development ───────────────────────────────────────
  # First stage: automatically creates feature branch + worktree
  # Worker codes, tests, commits, and pushes in an isolated worktree
  - name: develop
    trigger: "card_enters 'Todo'"       # Triggered when card enters Todo state
    card_state: Inprogress              # Card state while worker is active
    agent: claude                       # AI agent: claude / codex / gemini
    # profile: fullstack                # Skill profile (optional, see ~/.coral/skills/dev-worker/references/)
    completion: git-evidence            # Complete when: branch has commits and is pushed
    on_complete: "move_card QA"         # On success: move card to QA
    on_fail:
      action: "label NEEDS-FIX"         # On failure: add label
      comment: "Development worker failed. Check logs and retry."

  # ── Stage 2: Integration / Merge ───────────────────────────────
  # Last stage: rebases and merges to target branch, then cleans worktree
  # queue: fifo ensures only one merge at a time to prevent conflicts
  - name: integrate
    trigger: "card_enters 'QA'"         # Triggered when card enters QA state
    card_state: QA                      # Card state while merging
    agent: claude                       # Agent for integration
    completion: fast-forward-merge      # Complete when: branch merged to target
    on_complete: "move_card Done"       # On success: move card to Done
    on_fail:
      action: "label MERGE-FAILED"      # On failure: add label
      comment: "Integration merge failed. Check branch conflicts."
    queue: fifo                         # Serialize merges to avoid conflicts

# ── Extension: Multi-stage Pipeline ──────────────────────────────
# Add more stages between develop and integrate:
#
#  # Code Review stage
#  - name: code-review
#    trigger: "card_enters 'CodeReview'"
#    card_state: CodeReview
#    agent: claude
#    profile: reviewer                  # Uses reviewer skill profile
#    completion: exit-code
#    on_complete: "move_card Testing"
#
#  # Automated Testing stage
#  - name: testing
#    trigger: "card_enters 'Testing'"
#    card_state: Testing
#    agent: codex                       # Use Codex for test execution
#    completion: exit-code
#    on_complete: "move_card QA"
#    on_fail:
#      action: "label TEST-FAILED"
#      comment: "Automated tests failed."
#
# When using multi-stage, change develop's on_complete to point to the next stage:
#   on_complete: "move_card CodeReview"
`);
    log.ok(`Created pipelines/ with sample template`);
  }

  // Initialize state.json
  const stateFile = resolve(instanceDir, 'runtime', 'state.json');
  if (!existsSync(stateFile)) {
    const { writeState } = await import('../core/state.js');
    const maxW = parseInt(String(flags.maxWorkers || '3'), 10) || 3;
    const { createIdleWorkerSlot } = await import('../core/state.js');
    const workers: Record<string, any> = {};
    for (let i = 1; i <= maxW; i++) {
      workers[`worker-${i}`] = createIdleWorkerSlot();
    }
    const initState = {
      workers, activeCards: {}, leases: {},
      worktreeEvidence: {}, sessions: {},
      integrationQueues: {}, worktreeCleanup: [],
      pendingPMActions: [],
    };
    writeState(stateFile, initState as any, 'project-init');
    log.ok('Initialized state.json');
  }

  // Cards directory — only create seq.txt; state subdirectories will be
  // created by MarkdownTaskBackend.bootstrap() based on pipeline YAML config
  const cardsDir = resolve(instanceDir, 'cards');
  if (!existsSync(cardsDir)) {
    mkdirSync(cardsDir, { recursive: true });
    writeFileSync(resolve(cardsDir, 'seq.txt'), '0\n');
    log.ok('Initialized cards/ directory (state dirs created on first use)');
  }

  // Initialize memory directory
  const memoryDir = resolve(HOME, '.coral', 'memory', 'projects', project);
  if (!existsSync(memoryDir)) {
    mkdirSync(memoryDir, { recursive: true });
    log.ok(`Created project memory at ${memoryDir}`);
  }

  log.ok(`Project ${project} initialized at ${instanceDir}`);
  console.log('\n  Next steps:\n');
  console.log(`  1. Create pipeline config:`);
  console.log(`     cp ${resolve(instanceDir, 'pipelines', 'sample.yaml.example')} ${resolve(instanceDir, 'pipelines', 'project.yaml')}`);
  console.log(`     vim ${resolve(instanceDir, 'pipelines', 'project.yaml')}`);
  console.log(`     Or use: sps agent --chat → "帮我创建 pipeline"`);
  console.log('');
  console.log(`  2. Add task cards:`);
  console.log(`     sps card add ${project} "task title" "description"`);
  console.log('');
  console.log(`  3. Start pipeline:`);
  console.log(`     sps tick ${project}`);
  console.log('');
  console.log(`  Optional: sps doctor ${project} --fix  (generate CLAUDE.md in repo)`);
  console.log('');
}
