/**
 * @module        projectInit
 * @description   项目初始化命令，从模板创建项目配置和目录结构
 *
 * @author        eddy
 * @organization  wykj
 * @ownership     wykj/eddy
 *
 * @created       2026-03-19
 * @updated       2026-04-03
 *
 * @role          command
 * @layer         command
 * @boundedContext system
 *
 * @trigger       sps init <project> [--force]
 * @inputs        项目名、--force 覆盖标志
 * @outputs       初始化后的项目目录和配置文件
 * @workflow      1. 查找模板目录 → 2. 创建项目目录 → 3. 复制模板文件 → 4. 写入配置
 */
import { chmodSync, copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { createInterface } from 'node:readline';
import { fileURLToPath } from 'node:url';
import { Logger } from '../core/logger.js';

const HOME = process.env.HOME || '/home/coral';
const __dirname = dirname(fileURLToPath(import.meta.url));

// Look for project-template relative to the package root (works for both npm install and source)
function findTemplateDir(): string {
  // When installed via npm: dist/commands/projectInit.js → ../../project-template
  const npmPath = resolve(__dirname, '..', '..', 'project-template');
  if (existsSync(npmPath)) return npmPath;
  // When running from source repo: src/commands/ → ../../../project-template
  const srcPath = resolve(__dirname, '..', '..', '..', 'project-template');
  if (existsSync(srcPath)) return srcPath;
  // Legacy fallback
  const legacyPath = resolve(HOME, 'jarvis-skills', 'coding-work-flow', 'project-template');
  if (existsSync(legacyPath)) return legacyPath;
  return npmPath; // default, will fail gracefully below
}

const TEMPLATE_DIR = findTemplateDir();

export async function executeProjectInit(
  project: string,
  flags: Record<string, boolean>,
): Promise<void> {
  const log = new Logger('project-init', project);

  if (!project) {
    log.error('Usage: sps project init <project>');
    process.exit(2);
  }

  const instanceDir = resolve(HOME, '.coral', 'projects', project);

  if (existsSync(instanceDir) && !flags.force) {
    log.error(`Project directory already exists: ${instanceDir}`);
    log.info('Use --force to overwrite templates (conf will NOT be overwritten)');
    process.exit(1);
  }

  // Create directory structure
  const dirs = [
    instanceDir,
    resolve(instanceDir, 'logs'),
    resolve(instanceDir, 'pm_meta'),
    resolve(instanceDir, 'runtime'),
  ];

  for (const dir of dirs) {
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
      log.ok(`Created ${dir}`);
    }
  }

  // Generate conf — interactive if new, skip if exists
  const confDst = resolve(instanceDir, 'conf');
  if (!existsSync(confDst) || flags.force) {
    const rl = createInterface({ input: process.stdin, output: process.stdout });
    const ask = (question: string, defaultValue?: string): Promise<string> => {
      const suffix = defaultValue ? ` [${defaultValue}]` : '';
      return new Promise((res) => {
        rl.question(`  ${question}${suffix}: `, (answer) => {
          res(answer.trim() || defaultValue || '');
        });
      });
    };

    console.log(`\n  Configure project: ${project}`);
    console.log('  Press Enter to accept default value.\n');

    // Required
    const projectDir = await ask('Repository path', resolve(HOME, 'projects', project));
    const pmTool = await ask('PM backend (markdown/plane/trello)', 'markdown');
    const mergeBranch = await ask('Merge target branch', 'main');
    const workerTool = await ask('Default worker agent (claude/codex)', 'claude');
    const maxWorkers = await ask('Max concurrent workers', '1');

    // Git remote (optional)
    console.log('\n  ── Git Remote (optional, leave blank to skip) ──');
    const gitlabProject = await ask('Git remote project path (e.g. user/repo)', '');
    const gitlabProjectId = gitlabProject ? await ask('GitLab project ID (number, blank if GitHub)', '') : '';

    // PM-specific
    let planeProjectId = '';
    let trelloBoardId = '';
    if (pmTool === 'plane') {
      console.log('\n  ── Plane ──');
      planeProjectId = await ask('Plane project ID', '');
    } else if (pmTool === 'trello') {
      console.log('\n  ── Trello ──');
      trelloBoardId = await ask('Trello board ID', '');
    }

    // Notification
    console.log('\n  ── Notifications ──');
    const matrixRoomId = await ask('Matrix room ID (blank to use global)', '');

    rl.close();

    // Build conf
    const lines: string[] = [
      '# ── Project Config ─────────────────────────────────────────────',
      `# Generated by: sps project init ${project} (${new Date().toISOString().slice(0, 10)})`,
      '',
      `export PROJECT_NAME="${project}"`,
      `export PROJECT_DIR="${projectDir}"`,
      '',
      '# ── Git Remote ───────────────────────────────────────────────',
    ];
    if (gitlabProject) lines.push(`export GITLAB_PROJECT="${gitlabProject}"`);
    else lines.push('# export GITLAB_PROJECT="user/repo"');
    if (gitlabProjectId) lines.push(`export GITLAB_PROJECT_ID="${gitlabProjectId}"`);
    else lines.push('# export GITLAB_PROJECT_ID=""');
    lines.push(`export GITLAB_MERGE_BRANCH="${mergeBranch}"`);
    lines.push('');

    lines.push('# ── PM Backend ───────────────────────────────────────────────');
    lines.push(`export PM_TOOL="${pmTool}"`);
    if (pmTool === 'plane' && planeProjectId) {
      lines.push(`export PLANE_PROJECT_ID="${planeProjectId}"`);
    }
    if (pmTool === 'trello' && trelloBoardId) {
      lines.push(`export TRELLO_BOARD_ID="${trelloBoardId}"`);
    }
    lines.push('');

    lines.push('# ── Pipeline ─────────────────────────────────────────────────');
    lines.push('export PIPELINE_LABEL="AI-PIPELINE"');
    lines.push('export MR_MODE="none"');
    lines.push('');

    lines.push('# ── Worker / Agent ───────────────────────────────────────────');
    lines.push(`export WORKER_TOOL="${workerTool}"`);
    lines.push('export WORKER_TRANSPORT="acp-sdk"');
    lines.push(`export MAX_CONCURRENT_WORKERS=${maxWorkers}`);
    lines.push('export MAX_ACTIONS_PER_TICK=3');
    lines.push('# export DEFAULT_WORKER_SKILLS="fullstack"');
    lines.push('');

    lines.push('# ── Timeouts & Policies ──────────────────────────────────────');
    lines.push('export INPROGRESS_TIMEOUT_HOURS=2');
    lines.push('export MONITOR_AUTO_QA=true');
    lines.push('export CONFLICT_DEFAULT="serial"');
    lines.push('');

    lines.push('# ── Notifications ────────────────────────────────────────────');
    if (matrixRoomId) {
      lines.push(`export MATRIX_ROOM_ID="${matrixRoomId}"`);
    } else {
      lines.push('# export MATRIX_ROOM_ID=""  # uses global from ~/.coral/env');
    }
    lines.push('');

    writeFileSync(confDst, lines.join('\n') + '\n');
    chmodSync(confDst, 0o600);
    log.ok(`Generated conf with your settings`);
  } else {
    log.info('conf already exists, skipping (use --force to regenerate)');
  }

  // Create empty pipeline_order.json if not exists
  const orderFile = resolve(instanceDir, 'pipeline_order.json');
  if (!existsSync(orderFile)) {
    writeFileSync(orderFile, '[]\n');
    log.ok('Created empty pipeline_order.json');
  }

  // Create pipelines directory with sample template
  const pipelinesDir = resolve(instanceDir, 'pipelines');
  if (!existsSync(pipelinesDir)) {
    mkdirSync(pipelinesDir, { recursive: true });
    const samplePath = resolve(pipelinesDir, 'sample.yaml.example');
    writeFileSync(samplePath, `# SPS Pipeline Configuration Sample
# Rename this file to project.yaml to activate it.
# Documentation: sps-pipeline skill or docs/design/17-pipeline-configuration-design.md

mode: project

# ── Card States ──────────────────────────────────────────────────
# Only 3 fixed roles required. Intermediate states come from stages.
states:
  backlog: Backlog       # SPS entry point (cards with AI-PIPELINE label)
  ready: Todo            # Environment ready, waiting for first stage
  done: Done             # Last stage completed

# ── Stages ───────────────────────────────────────────────────────
# Define your development workflow. Minimum 1 stage.
# Each stage triggers on a card state, launches a worker, and moves the card on completion.

stages:
  # Stage 1: Development (first stage creates branch + worktree automatically)
  - name: develop
    trigger: "card_enters 'Todo'"
    card_state: Inprogress
    agent: claude                   # claude / codex / gemini
    # profile: fullstack            # skill profile (optional, comma-separated)
    completion: git-evidence        # git-evidence / fast-forward-merge / exit-code
    on_complete: "move_card QA"
    on_fail:
      action: "label NEEDS-FIX"
      comment: "Development worker failed."

  # Stage 2: Integration (last stage releases resources + cleans worktree)
  - name: integrate
    trigger: "card_enters 'QA'"
    card_state: QA
    agent: claude
    completion: fast-forward-merge
    on_complete: "move_card Done"
    on_fail:
      action: "label MERGE-FAILED"
      comment: "Integration merge failed."
    queue: fifo                     # serialize merges to avoid conflicts

# ── Optional: Multi-stage example ────────────────────────────────
# Uncomment to add a code review stage between develop and integrate:
#
#  - name: code-review
#    trigger: "card_enters 'CodeReview'"
#    card_state: CodeReview
#    agent: claude
#    profile: reviewer
#    completion: exit-code
#    on_complete: "move_card QA"
#
# Then change develop's on_complete to: "move_card CodeReview"
`);
    log.ok(`Created pipelines/ with sample template`);
  }

  // Initialize state.json
  const stateFile = resolve(instanceDir, 'runtime', 'state.json');
  if (!existsSync(stateFile)) {
    const { writeState } = await import('../core/state.js');
    const maxW = parseInt(String(flags.maxWorkers || '3'), 10) || 3;
    const { createIdleWorkerSlot } = await import('../core/state.js');
    const workers: Record<string, any> = {};
    for (let i = 1; i <= maxW; i++) {
      workers[`worker-${i}`] = createIdleWorkerSlot();
    }
    const initState = {
      workers, activeCards: {}, leases: {},
      worktreeEvidence: {}, sessions: {},
      integrationQueues: {}, worktreeCleanup: [],
      pendingPMActions: [],
    };
    writeState(stateFile, initState as any, 'project-init');
    log.ok('Initialized state.json');
  }

  // Cards directory — only create seq.txt; state subdirectories will be
  // created by MarkdownTaskBackend.bootstrap() based on pipeline YAML config
  const cardsDir = resolve(instanceDir, 'cards');
  if (!existsSync(cardsDir)) {
    mkdirSync(cardsDir, { recursive: true });
    writeFileSync(resolve(cardsDir, 'seq.txt'), '0\n');
    log.ok('Initialized cards/ directory (state dirs created on first use)');
  }

  // Initialize memory directory
  const memoryDir = resolve(HOME, '.coral', 'memory', 'projects', project);
  if (!existsSync(memoryDir)) {
    mkdirSync(memoryDir, { recursive: true });
    log.ok(`Created project memory at ${memoryDir}`);
  }

  log.ok(`Project ${project} initialized at ${instanceDir}`);
  console.log('\n  Next steps:\n');
  console.log(`  1. Create pipeline config:`);
  console.log(`     cp ${resolve(instanceDir, 'pipelines', 'sample.yaml.example')} ${resolve(instanceDir, 'pipelines', 'project.yaml')}`);
  console.log(`     vim ${resolve(instanceDir, 'pipelines', 'project.yaml')}`);
  console.log(`     Or use: sps agent --chat → "帮我创建 pipeline"`);
  console.log('');
  console.log(`  2. Add task cards:`);
  console.log(`     sps card add ${project} "task title" "description"`);
  console.log('');
  console.log(`  3. Start pipeline:`);
  console.log(`     sps tick ${project}`);
  console.log('');
  console.log(`  Optional: sps doctor ${project} --fix  (generate CLAUDE.md in repo)`);
  console.log('');
}
