import { existsSync, mkdirSync, writeFileSync, readFileSync, chmodSync } from 'node:fs';
import { resolve } from 'node:path';
import { createInterface } from 'node:readline';
import { Logger } from '../core/logger.js';

const HOME = process.env.HOME || '/home/coral';
const ENV_PATH = resolve(HOME, '.jarvis.env');
const PROJECTS_DIR = resolve(HOME, '.projects');

function createPrompt(): { ask: (question: string, defaultValue?: string) => Promise<string>; close: () => void } {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  return {
    ask: (question: string, defaultValue?: string): Promise<string> => {
      const suffix = defaultValue ? ` [${defaultValue}]` : '';
      return new Promise((resolve) => {
        rl.question(`  ${question}${suffix}: `, (answer) => {
          resolve(answer.trim() || defaultValue || '');
        });
      });
    },
    close: () => rl.close(),
  };
}

export async function executeSetup(flags: Record<string, boolean>): Promise<void> {
  const log = new Logger('setup', '');
  const prompt = createPrompt();

  console.log('\n  SPS CLI — Initial Setup\n');

  // ─── Step 1: ~/.projects directory ─────────────────────────────
  if (!existsSync(PROJECTS_DIR)) {
    mkdirSync(PROJECTS_DIR, { recursive: true });
    log.ok(`Created ${PROJECTS_DIR}`);
  } else {
    log.ok(`${PROJECTS_DIR} already exists`);
  }

  // ─── Step 2: ~/.jarvis.env ─────────────────────────────────────
  if (existsSync(ENV_PATH) && !flags.force) {
    log.ok(`${ENV_PATH} already exists (use --force to reconfigure)`);
  } else {
    console.log('\n  Configure global credentials (~/.jarvis.env)\n');
    console.log('  Press Enter to skip optional fields.\n');

    // GitLab
    console.log('  ── GitLab ──');
    const gitlabUrl = await prompt.ask('GITLAB_URL (e.g. https://git.example.com)');
    const gitlabToken = await prompt.ask('GITLAB_TOKEN');
    const gitlabSshHost = await prompt.ask('GITLAB_SSH_HOST', gitlabUrl ? new URL(gitlabUrl).hostname : '');
    const gitlabSshPort = await prompt.ask('GITLAB_SSH_PORT', '22');

    // PM Backend
    console.log('\n  ── PM Backend (Plane) ──');
    const planeUrl = await prompt.ask('PLANE_URL (leave empty if not using Plane)');
    const planeApiKey = planeUrl ? await prompt.ask('PLANE_API_KEY') : '';
    const planeWorkspace = planeUrl ? await prompt.ask('PLANE_WORKSPACE_SLUG') : '';

    // Trello
    console.log('\n  ── PM Backend (Trello) ──');
    const trelloApiKey = await prompt.ask('TRELLO_API_KEY (leave empty if not using Trello)');
    const trelloToken = trelloApiKey ? await prompt.ask('TRELLO_TOKEN') : '';

    // Matrix notifications
    console.log('\n  ── Notifications (Matrix) ──');
    const matrixHomeserver = await prompt.ask('MATRIX_HOMESERVER (leave empty if not using Matrix)');
    const matrixToken = matrixHomeserver ? await prompt.ask('MATRIX_TOKEN') : '';
    const matrixRoomId = matrixHomeserver ? await prompt.ask('MATRIX_ROOM_ID') : '';

    // Build env file
    const lines: string[] = [
      '# SPS CLI — Global Credentials',
      `# Generated by: sps setup (${new Date().toISOString().slice(0, 10)})`,
      '',
    ];

    if (gitlabUrl || gitlabToken) {
      lines.push('# ── GitLab ──────────────────────────────────────────');
      if (gitlabUrl) lines.push(`export GITLAB_URL="${gitlabUrl}"`);
      if (gitlabToken) lines.push(`export GITLAB_TOKEN="${gitlabToken}"`);
      if (gitlabSshHost) lines.push(`export GITLAB_SSH_HOST="${gitlabSshHost}"`);
      if (gitlabSshPort && gitlabSshPort !== '22') lines.push(`export GITLAB_SSH_PORT="${gitlabSshPort}"`);
      lines.push('');
    }

    if (planeUrl) {
      lines.push('# ── Plane ───────────────────────────────────────────');
      lines.push(`export PLANE_URL="${planeUrl}"`);
      if (planeApiKey) lines.push(`export PLANE_API_KEY="${planeApiKey}"`);
      if (planeWorkspace) lines.push(`export PLANE_WORKSPACE_SLUG="${planeWorkspace}"`);
      lines.push('');
    }

    if (trelloApiKey) {
      lines.push('# ── Trello ──────────────────────────────────────────');
      lines.push(`export TRELLO_API_KEY="${trelloApiKey}"`);
      if (trelloToken) lines.push(`export TRELLO_TOKEN="${trelloToken}"`);
      lines.push('');
    }

    if (matrixHomeserver) {
      lines.push('# ── Matrix (Notifications) ──────────────────────────');
      lines.push(`export MATRIX_HOMESERVER="${matrixHomeserver}"`);
      if (matrixToken) lines.push(`export MATRIX_TOKEN="${matrixToken}"`);
      if (matrixRoomId) lines.push(`export MATRIX_ROOM_ID="${matrixRoomId}"`);
      lines.push('');
    }

    writeFileSync(ENV_PATH, lines.join('\n') + '\n');
    chmodSync(ENV_PATH, 0o600);
    log.ok(`Created ${ENV_PATH} (permissions: 600)`);
  }

  // ─── Summary ───────────────────────────────────────────────────
  console.log('\n  Setup complete! Next steps:\n');
  console.log('  1. Source the env file:');
  console.log(`     source ${ENV_PATH}`);
  console.log('');
  console.log('  2. (Optional) Auto-load on shell startup:');
  console.log(`     echo 'source ${ENV_PATH}' >> ~/.bashrc`);
  console.log('');
  console.log('  3. Initialize your first project:');
  console.log('     sps project init <project-name>');
  console.log('');
  console.log('  4. Edit the project config:');
  console.log('     vim ~/.projects/<project-name>/conf');
  console.log('');
  console.log('  5. Run health check:');
  console.log('     sps doctor <project-name> --fix');
  console.log('');

  prompt.close();
}
